### ISSUE TITLE
How to test a trained discriminator separately???

### ISSUE THREAD

**Issue by anamika06jain** [diegoalejogm/gans#11]
I have a doubt, at the end of the training phase we have both generator and discriminator. Now i only want to test the discriminator... How can i do that?

**Comment by diegoalejogm** [comment]
You can store the discriminator on [Pytorch](https://mail.google.com/mail/u/0/#inbox) or  [TensorFlow](https://www.tensorflow.org/tutorials/keras/save_and_load).

Once you have your model on a variable (e.g. *discriminator*) , and the data you want to test (*fake_data*) you can do:
`discriminator(fake_data)`
