### ISSUE TITLE
Using own training set

### ISSUE THREAD

**Issue by ghost** [diegoalejogm/gans#6]
Can you train both the Vanilla and the DCN networks with your own data set or some data set like ImageNet for example. and If so how would you do it? for both Pytorch and Tensorflow.

**Comment by HamzahNizami** [comment]
any luck with this?

**Comment by meltemiatay** [comment]
Use data loaders for pytorch, and costumize them accordingly (for example change image size according to your dataset)
Data loaders example:https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

**Comment by diegoalejogm** [comment]
Hi, @i-am-mel-dev is correct. You can create a new loader to put the data in!
